@startuml
'Скрыть иконку класса
hide circle
'Скрыть раздел с полями если он пустой
hide empty fields
'Скрыть раздел с методами если он пустой
hide empty methods
'Скрыть поля и методы
'hide members

    class UserInfo{
        Long avatarId
        String name
        UserTypeEnum userType
        Map<String, String> publicInfo
        Long userStatusId
        Locale locale
        TimeZone timeZone
    }
    class Chat{
        String label
        ChatTypeEnum chatType
        Long numberingId
        Long orderNumber
    }
    class Message {
        Long chatId
        String text
        Long fileId
        Long childChatId
        MessageTypeEnum messageType
        Long parentMessageId
    }
    class FileInfo{
    	String name
    	String mimeType
    	Long fileSize
    	String path
    	FileAccessTypeEnum fileAccessType
    	Integer crc32
    	Long lastOpenTime
    	Boolean gzipOn
    }
    class MessageLog {
        Long messageId
        String oldText
    }
    class MessageTag {
        Long messageId
        Long tagId
        String value
    }
    class MessageToUser {
        Long messageId
        Long userId
        MessageStatusEnum messageStatus
        FeedbackFeedbackEnum feedbackFeedback
    }
    class MessageFeedback {
        Long messageId
        Integer feedback
    }
    class Tag{
        String tag
        TagTypeEnum tagType
        String description
        Boolean leftMenuShow
        Boolean headerShow
        TagGroupEnum tagGroup
    }
    class UserContact{
        Long parentUserId
        Long childUserId
        UserContactStatusEnum userContactStatus
        String label
        Long chatId
    }
    class UserFilter {
         Long userId
         FilterPageTypeEnum pageType
         String filterLabel
         JSON data
    }
    class UserLink {
         Long parentUserId
         Long childUserId
         UserLinkEnum userLinkType
    }
    class UserLog {
    	Long userId
        public String fieldName
        public String fieldOldValue
        public String fieldNewValue
        public String comment
    }
    class UserStatus  {
        String label
        UserStatusTypeEnum userStatusType
        Integer weight
        Integer color
    }
    class UserTree {
         Long parentUserId
         Long childUserId
         Integer distance
    }
    class ChatToUser{
        Long chatId
        Long userId
        boolean favorite
        ChatToUserTypeEnum chatToUserType
        boolean mute
    }
    class ChatToUserLastMessage{
        Long chatToUserId
        Long messageId
    }
    class ChatTree{
        Long parentChatId
        Long childChatId
        Integer distance
    }
    class ChatPriority{
        Long chatId
        Long priority
    }
    class ChatWork{
        Long chatId
        Long userId
        Long startTime
        Long endTime
    }
    class ChatReminder{
        Long chatId
        Long userId
        String text
        Long reminderTime
    }
    class ChatTagGroup {
        Long chatId
        TagGroupEnum tagGroup
        Long messageTagId
    }
    class Numbering {
        Long userId
        String prefix
        Long maxNumber
    }
    class UserEntryPoint {
        Long userId
        Boolean validate
        EntryPointTypeEnum entryPointType
        String clientId
        String credential
	}
    class UserSession  {
        Long userEntryPointId
        String token
        Long userEntryPointId
    }
    class UserSessionFail  {
        Long userEntryPointId
        String ipAddress
        String comment
    }
    class RequestLog {
        String token
        String eventId
        Long startInvoke
        Long endInvoke
        String errorStackTrace
    }

UserInfo -[#00FF00]- UserContact
UserInfo -[#00FF00]left-{ UserEntryPoint
UserInfo -[#00FF00]-{ UserFilter
UserInfo -[#00FF00]-{ UserLink
UserInfo -[#00FF00]-{ UserLog
UserInfo -[#00FF00]-{ UserTree
UserInfo -[#00FF00]-{ UserStatus
UserInfo -[#00FF00]-{ ChatWork
UserInfo -[#00FF00]-{ ChatReminder
UserInfo -[#00FF00]-{ ChatToUser
UserInfo -[#00FF00]-{ MessageToUser
UserInfo -[#00FF00]-{ Numbering

UserInfo -[#000000]right-{ Chat

Chat -[#FF0000]-{ ChatReminder
Chat -[#FF0000]-{ ChatTagGroup
Chat -[#FF0000]-{ ChatToUser
Chat -[#FF0000]-{ ChatTree
Chat -[#FF0000]-{ ChatWork
Chat -[#FF0000]-{ UserContact
Chat -[#FF0000]- ChatPriority

Chat -[#000000]right-{ Message

Message -[#0000FF]- Message : hierarchy
Message -[#0000FF]-{ MessageToUser
Message -[#0000FF]-{ MessageLog
Message -[#0000FF]-{ MessageTag
Message -[#0000FF]-{ ChatToUserLastMessage
Message }-[#000000]- FileInfo
Message -[#0000FF]- MessageFeedback

MessageTag }-[#000000]- Tag
UserEntryPoint -[#000000]down-{ UserSession
UserSession -[#000000]down-{ RequestLog
UserEntryPoint -[#000000]-{ UserSessionFail

UserLink -[hidden]down- UserTree
UserStatus -[hidden]down- UserLog
UserLog -[hidden]down- UserFilter
UserFilter -[hidden]down- Numbering
UserContact -[hidden]down- ChatWork
ChatWork -[hidden]down- ChatReminder
ChatTagGroup -[hidden]down- ChatTree
ChatToUser -down- ChatToUserLastMessage

@enduml